// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API Responce",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "image"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "RawProduct": {
      "properties": {
        "id": {
          "title": "RawProduct.id",
          "type": "number"
        },
        "title": {
          "title": "RawProduct.title",
          "type": "string"
        },
        "price": {
          "title": "RawProduct.price",
          "type": "number"
        },
        "description": {
          "title": "RawProduct.description",
          "type": "string"
        },
        "images": {
          "items": {
            "title": "RawProduct.images.[]",
            "type": "string"
          },
          "title": "RawProduct.images",
          "type": "array"
        },
        "creationAt": {
          "title": "RawProduct.creationAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "RawProduct.updatedAt",
          "type": "string"
        },
        "category": {
          "properties": {
            "id": {
              "title": "RawProduct.category.id",
              "type": "number"
            },
            "name": {
              "title": "RawProduct.category.name",
              "type": "string"
            },
            "image": {
              "title": "RawProduct.category.image",
              "type": "string"
            },
            "creationAt": {
              "title": "RawProduct.category.creationAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "RawProduct.category.updatedAt",
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "image",
            "creationAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "title": "RawProduct.category",
          "type": "object"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "images",
        "creationAt",
        "updatedAt",
        "category"
      ],
      "additionalProperties": false,
      "title": "RawProduct",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};